return {
  -- "olimorris/codecompanion.nvim",
  -- dependencies = {
  --   "nvim-lua/plenary.nvim",
  --   "nvim-treesitter/nvim-treesitter",
  -- },
  -- opts = {
  --   adapters = {
  --     openai = function()
  --       return require("codecompanion.adapters").extend("openai", {
  --         opts = {
  --           stream = true,
  --         },
  --         env = {
  --           api_key = os.getenv("OPENAI_API_KEY"),
  --         },
  --         schema = {
  --           model = {
  --             default = function()
  --               return "gpt-4.1"
  --             end,
  --           },
  --         },
  --       })
  --     end,
  --   },
  --   strategies = {
  --     chat = {
  --       adapter = "openai",
  --     },
  --     inline = {
  --       adapter = "openai",
  --     },
  --   },
  -- },
}
